# Generated by Django 6.1 on 2026-08-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserSync',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=64, unique=True)),
                ('gl_name', models.CharField(blank=True, max_length=64, null=True)),
                ('user_password', models.CharField(max_length=128)),
                ('user_time', models.BigIntegerField(default=0)),
                ('puser_time', models.BigIntegerField(default=0)),
                ('scope_name', models.CharField(blank=True, max_length=64, null=True)),
                ('mount_name', models.CharField(blank=True, max_length=64, null=True)),
                ('device_type', models.CharField(blank=True, max_length=64, null=True)),
                ('sn', models.CharField(blank=True, max_length=64, null=True)),
                ('email', models.CharField(blank=True, max_length=128, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=128, null=True)),
                ('telephone', models.CharField(blank=True, max_length=64, null=True)),
                ('is_active', models.SmallIntegerField(default=1)),
                ('is_manual', models.SmallIntegerField(default=0)),
                ('facade_cad_enabled', models.SmallIntegerField(default=0)),
                ('topo_cad_enabled', models.SmallIntegerField(default=0)),
                ('facade_foto_enabled', models.SmallIntegerField(default=0)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users_sync',
            },
        ),
    ]
