# Generated by Django 6.1 on 2026-08-21 10:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('station_code', models.CharField(blank=True, max_length=32, null=True)),
                ('name', models.CharField(max_length=128)),
                ('host', models.CharField(max_length=255)),
                ('port', models.IntegerField(default=2101)),
                ('mountpoint', models.CharField(max_length=128)),
                ('ntrip_user', models.CharField(blank=True, max_length=128, null=True)),
                ('ntrip_password', models.CharField(blank=True, max_length=128, null=True)),
                ('lat', models.DecimalField(decimal_places=7, max_digits=10)),
                ('lon', models.DecimalField(decimal_places=7, max_digits=10)),
                ('ecef_x', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('ecef_y', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('ecef_z', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('rinex_path', models.CharField(blank=True, max_length=255, null=True)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('is_enabled', models.SmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'stations',
            },
        ),
        migrations.CreateModel(
            name='StationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('unknown', 'Unknown')], max_length=10)),
                ('bytes_received', models.IntegerField(default=0)),
                ('error_message', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'station_log',
            },
        ),
        migrations.CreateModel(
            name='StationStatus',
            fields=[
                ('station', models.OneToOneField(db_column='station_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='status', serialize=False, to='stations.station')),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('last_check_at', models.DateTimeField(blank=True, null=True)),
                ('last_data_at', models.DateTimeField(blank=True, null=True)),
                ('bytes_received', models.IntegerField(default=0)),
                ('last_error', models.CharField(blank=True, max_length=255, null=True)),
                ('ftp_checked_at', models.DateTimeField(blank=True, null=True)),
                ('ftp_last_data_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'station_status',
            },
        ),
        migrations.AddIndex(
            model_name='station',
            index=models.Index(fields=['host', 'port', 'mountpoint'], name='idx_host_mount'),
        ),
        migrations.AddField(
            model_name='stationlog',
            name='station',
            field=models.ForeignKey(db_column='station_id', on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='stations.station'),
        ),
        migrations.AddIndex(
            model_name='stationlog',
            index=models.Index(fields=['station', 'checked_at'], name='idx_station_time'),
        ),
    ]
