# Generated by Django 6.1 on 2026-08-24 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('users', '0002_usersync_storage_quota_bytes'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=1024)),
                ('can_write', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shared_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.admin')),
                ('shared_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.usersync')),
                ('shared_with_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.admin')),
                ('shared_with_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.usersync')),
            ],
            options={
                'db_table': 'storage_shared_access',
                'indexes': [models.Index(fields=['shared_with_admin'], name='idx_shared_access_with_admin'), models.Index(fields=['shared_with_user'], name='idx_shared_access_with_user')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('shared_by_admin__isnull', False), ('shared_by_user__isnull', True)), models.Q(('shared_by_admin__isnull', True), ('shared_by_user__isnull', False)), _connector='OR'), name='chk_shared_access_by_owner'), models.CheckConstraint(condition=models.Q(models.Q(('shared_with_admin__isnull', False), ('shared_with_user__isnull', True)), models.Q(('shared_with_admin__isnull', True), ('shared_with_user__isnull', False)), _connector='OR'), name='chk_shared_access_with_owner')],
            },
        ),
    ]
