# Generated by Django 6.1 on 2026-08-21 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlamProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('target_crs_epsg', models.IntegerField(blank=True, null=True)),
                ('target_crs_wkt', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slam_projects_created', to='core.admin')),
            ],
            options={
                'db_table': 'slam_projects',
            },
        ),
        migrations.CreateModel(
            name='SlamScan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploaded', max_length=12)),
                ('raw_file_path', models.CharField(blank=True, max_length=255, null=True)),
                ('bag_lidar_enabled', models.SmallIntegerField(default=1)),
                ('rtk_fixed', models.SmallIntegerField(blank=True, null=True)),
                ('skip_georeference', models.SmallIntegerField(default=0)),
                ('num_points', models.BigIntegerField(blank=True, null=True)),
                ('source_format', models.CharField(blank=True, max_length=16, null=True)),
                ('crs_epsg', models.IntegerField(blank=True, null=True)),
                ('crs_proj4', models.CharField(blank=True, max_length=500, null=True)),
                ('bbox_min_lon', models.FloatField(blank=True, null=True)),
                ('bbox_min_lat', models.FloatField(blank=True, null=True)),
                ('bbox_max_lon', models.FloatField(blank=True, null=True)),
                ('bbox_max_lat', models.FloatField(blank=True, null=True)),
                ('error_message', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slam_scans_created', to='core.admin')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='slam_pipeline.slamproject')),
            ],
            options={
                'db_table': 'slam_scans',
            },
        ),
        migrations.CreateModel(
            name='SlamProcessedAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('intermediate_laz', 'intermediate_laz'), ('las', 'las'), ('copc', 'copc'), ('mesh', 'mesh'), ('splat', 'splat')], max_length=20)),
                ('step', models.CharField(blank=True, max_length=20, null=True)),
                ('file_path', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='slam_pipeline.slamscan')),
            ],
            options={
                'db_table': 'slam_processed_assets',
            },
        ),
        migrations.CreateModel(
            name='SlamJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipeline_step', models.CharField(choices=[('compute_slam', 'compute_slam'), ('decode_raw', 'decode_raw'), ('filter_outliers', 'filter_outliers'), ('bin_to_rinex', 'bin_to_rinex'), ('ppk_correction', 'ppk_correction'), ('colorize', 'colorize'), ('georeference', 'georeference'), ('build_octree', 'build_octree')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('error', 'Error'), ('skipped', 'Skipped')], default='pending', max_length=12)),
                ('stall_retries', models.IntegerField(default=0)),
                ('error_message', models.CharField(blank=True, max_length=2000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='slam_pipeline.slamscan')),
            ],
            options={
                'db_table': 'slam_jobs',
            },
        ),
        migrations.CreateModel(
            name='SlamScanInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('trajectory', 'trajectory'), ('rover_obs', 'rover_obs'), ('base_rinex', 'base_rinex'), ('nav', 'nav'), ('rover_ppkraw_bin', 'rover_ppkraw_bin'), ('base_bin', 'base_bin'), ('frame_pose', 'frame_pose'), ('project_info', 'project_info'), ('calibration', 'calibration'), ('camera_frames', 'camera_frames')], max_length=20)),
                ('file_path', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='slam_pipeline.slamscan')),
            ],
            options={
                'db_table': 'slam_scan_inputs',
            },
        ),
        migrations.AddIndex(
            model_name='slamscan',
            index=models.Index(fields=['project', 'created_at'], name='idx_slam_scans_project'),
        ),
        migrations.AddIndex(
            model_name='slamprocessedasset',
            index=models.Index(fields=['scan', 'asset_type'], name='idx_slam_assets_scan'),
        ),
        migrations.AddIndex(
            model_name='slamjob',
            index=models.Index(fields=['status', 'created_at'], name='idx_slam_jobs_status'),
        ),
        migrations.AddConstraint(
            model_name='slamjob',
            constraint=models.UniqueConstraint(fields=('scan', 'pipeline_step'), name='uq_slam_job_scan_step'),
        ),
        migrations.AddConstraint(
            model_name='slamscaninput',
            constraint=models.UniqueConstraint(fields=('scan', 'kind'), name='uq_slam_input_scan_kind'),
        ),
    ]
