# Generated by Django 6.1 on 2026-08-21 10:37

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacadeCadSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloud_name', models.CharField(blank=True, max_length=255, null=True)),
                ('layers_json', models.TextField(default='{}')),
                ('ucs_json', models.TextField(default='{}')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.admin')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.usersync')),
            ],
            options={
                'db_table': 'facade_cad_sessions',
            },
        ),
        migrations.CreateModel(
            name='FacadeCadEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('pl', 'Polyline'), ('ci', 'Circle'), ('ar', 'Arc'), ('el', 'Ellipse'), ('tx', 'Text'), ('pt', 'Point')], max_length=4)),
                ('layer', models.CharField(default='0', max_length=64)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=0)),
                ('extra', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='cad_sessions.facadecadsession')),
            ],
            options={
                'db_table': 'facade_cad_entities',
            },
        ),
        migrations.CreateModel(
            name='FacadeFotoSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_json', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.admin')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.usersync')),
            ],
            options={
                'db_table': 'facade_foto_sessions',
            },
        ),
        migrations.CreateModel(
            name='TopoCadSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloud_name', models.CharField(blank=True, max_length=255, null=True)),
                ('layers_json', models.TextField(default='{}')),
                ('ucs_json', models.TextField(default='{}')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.admin')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.usersync')),
            ],
            options={
                'db_table': 'topo_cad_sessions',
            },
        ),
        migrations.CreateModel(
            name='TopoCadEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('pl', 'Polyline'), ('ci', 'Circle'), ('ar', 'Arc'), ('el', 'Ellipse'), ('tx', 'Text'), ('pt', 'Point')], max_length=4)),
                ('layer', models.CharField(default='0', max_length=64)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=0)),
                ('extra', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='cad_sessions.topocadsession')),
            ],
            options={
                'db_table': 'topo_cad_entities',
            },
        ),
        migrations.AddConstraint(
            model_name='facadecadsession',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('admin__isnull', False), ('user__isnull', True)), models.Q(('admin__isnull', True), ('user__isnull', False)), _connector='OR'), name='chk_facade_cad_session_owner'),
        ),
        migrations.AddConstraint(
            model_name='facadecadsession',
            constraint=models.UniqueConstraint(fields=('admin',), name='uq_facade_cad_session_admin'),
        ),
        migrations.AddConstraint(
            model_name='facadecadsession',
            constraint=models.UniqueConstraint(fields=('user',), name='uq_facade_cad_session_user'),
        ),
        migrations.AddIndex(
            model_name='facadecadentity',
            index=models.Index(fields=['session'], name='idx_fcad_entities_sess'),
        ),
        migrations.AddConstraint(
            model_name='facadefotosession',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('admin__isnull', False), ('user__isnull', True)), models.Q(('admin__isnull', True), ('user__isnull', False)), _connector='OR'), name='chk_facade_foto_session_owner'),
        ),
        migrations.AddConstraint(
            model_name='facadefotosession',
            constraint=models.UniqueConstraint(fields=('admin',), name='uq_facade_foto_session_admin'),
        ),
        migrations.AddConstraint(
            model_name='facadefotosession',
            constraint=models.UniqueConstraint(fields=('user',), name='uq_facade_foto_session_user'),
        ),
        migrations.AddConstraint(
            model_name='topocadsession',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('admin__isnull', False), ('user__isnull', True)), models.Q(('admin__isnull', True), ('user__isnull', False)), _connector='OR'), name='chk_topo_cad_session_owner'),
        ),
        migrations.AddConstraint(
            model_name='topocadsession',
            constraint=models.UniqueConstraint(fields=('admin',), name='uq_topo_cad_session_admin'),
        ),
        migrations.AddConstraint(
            model_name='topocadsession',
            constraint=models.UniqueConstraint(fields=('user',), name='uq_topo_cad_session_user'),
        ),
        migrations.AddIndex(
            model_name='topocadentity',
            index=models.Index(fields=['session'], name='idx_topo_cad_entities_session'),
        ),
    ]
