# Generated by Django 6.1 on 2026-08-22 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersync',
            name='storage_quota_bytes',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
