# Generated by Django 6.1 on 2026-08-21 10:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tour_groups',
            },
        ),
        migrations.CreateModel(
            name='PgConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('host', models.CharField(max_length=255)),
                ('port', models.IntegerField(default=5432)),
                ('dbname', models.CharField(max_length=128)),
                ('username', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=255)),
                ('sslmode', models.CharField(default='prefer', max_length=20)),
                ('is_default', models.SmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pg_connections_created', to='core.admin')),
            ],
            options={
                'db_table': 'pg_connections',
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('lat', models.DecimalField(decimal_places=7, max_digits=10)),
                ('lon', models.DecimalField(decimal_places=7, max_digits=10)),
                ('file_path', models.CharField(max_length=255)),
                ('file_format', models.CharField(choices=[('ply', 'PLY'), ('splat', 'Splat'), ('ksplat', 'KSplat'), ('las', 'LAS')], default='ksplat', max_length=10)),
                ('is_enabled', models.SmallIntegerField(default=1)),
                ('is_public', models.SmallIntegerField(default=0)),
                ('pg_synced_at', models.DateTimeField(blank=True, null=True)),
                ('pg_sync_error', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tours_created', to='core.admin')),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tours_created', to='users.usersync')),
                ('pg_connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tours', to='tours.pgconnection')),
            ],
            options={
                'db_table': 'tours',
            },
        ),
        migrations.CreateModel(
            name='TourLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('color', models.CharField(default='#ff3b30', max_length=7)),
                ('is_visible', models.SmallIntegerField(default=1)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='tours.tour')),
            ],
            options={
                'db_table': 'tour_layers',
            },
        ),
        migrations.CreateModel(
            name='TourFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=255)),
                ('file_format', models.CharField(choices=[('ply', 'PLY'), ('splat', 'Splat'), ('ksplat', 'KSplat'), ('las', 'LAS')], max_length=10)),
                ('sort_order', models.IntegerField(default=0)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='tours.tour')),
            ],
            options={
                'db_table': 'tour_files',
                'indexes': [models.Index(fields=['tour', 'sort_order'], name='idx_tour_files_tour')],
            },
        ),
        migrations.CreateModel(
            name='TourAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom_type', models.CharField(choices=[('point', 'Point'), ('polyline', 'Polyline'), ('polygon', 'Polygon')], max_length=10)),
                ('coordinates', models.TextField()),
                ('label', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='tours.tourlayer')),
            ],
            options={
                'db_table': 'tour_annotations',
                'indexes': [models.Index(fields=['layer'], name='idx_annotations_layer')],
            },
        ),
    ]


