# Generated by Django 6.1 on 2026-08-24 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('users', '0002_usersync_storage_quota_bytes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_group', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'chat_conversations',
            },
        ),
        migrations.CreateModel(
            name='ConversationParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.admin')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='chat.conversation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.usersync')),
            ],
            options={
                'db_table': 'chat_conversation_participants',
                'indexes': [models.Index(fields=['admin', 'conversation'], name='idx_chat_participant_admin'), models.Index(fields=['user', 'conversation'], name='idx_chat_participant_user')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('admin__isnull', False), ('user__isnull', True)), models.Q(('admin__isnull', True), ('user__isnull', False)), _connector='OR'), name='chk_chat_participant_owner')],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation')),
                ('sender_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.admin')),
                ('sender_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.usersync')),
            ],
            options={
                'db_table': 'chat_messages',
                'indexes': [models.Index(fields=['conversation', 'created_at'], name='idx_chat_messages_conv_time')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('sender_admin__isnull', False), ('sender_user__isnull', True)), models.Q(('sender_admin__isnull', True), ('sender_user__isnull', False)), _connector='OR'), name='chk_chat_message_sender')],
            },
        ),
    ]
