# Generated by Django 6.1 on 2026-08-21 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RinexRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stations', models.CharField(max_length=500)),
                ('date_from_utc', models.DateTimeField()),
                ('date_to_utc', models.DateTimeField()),
                ('want_obs', models.SmallIntegerField(default=1)),
                ('want_nav', models.SmallIntegerField(default=1)),
                ('merge_by_day', models.SmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('error', 'Error')], default='pending', max_length=12)),
                ('result_path', models.CharField(blank=True, max_length=255, null=True)),
                ('file_count', models.IntegerField(blank=True, null=True)),
                ('error_message', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rinex_requests', to='core.admin')),
            ],
            options={
                'db_table': 'rinex_requests',
                'indexes': [models.Index(fields=['status', 'created_at'], name='idx_rinex_requests_status'), models.Index(fields=['created_by', 'created_at'], name='idx_rinex_requests_creator')],
            },
        ),
    ]
